name: release-pc-windows-only
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'release version/tag'
        required: true
        default: 'v3.5.8'
      pnpm_version:
        description: 'pnpm@x.x.x'
        required: true
        default: 'latest'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ github.event.inputs.pnpm_version }}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Checkout SiYuan Source Code
        uses: actions/checkout@v4
        with:
          repository: siyuan-note/siyuan
          ref: ${{ github.event.inputs.release_version }}
          path: siyuan
      - name: Apply VIP Patches
        run: |
          cd siyuan
          git apply ../patches/siyuan/*.patch
      - name: Build Frontend Resources
        run: |
          cd siyuan/app
          pnpm install
          pnpm build
      - name: Build Windows Kernel
        run: |
          cd siyuan/kernel
          go build -o ../app/kernel-windows/SiYuan-Kernel.exe -s -w -H=windowsgui -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod ./cmd/kernel
      - name: Build Windows Installer
        run: |
          cd siyuan/app
          pnpm run dist:win
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_version }}-patched
          files: siyuan/app/dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
